### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by vitaliy1379** [superdima05/deezer-grabber-server#2]
Привет, можно с вами связаться через телеграм или еще как , например вы можете написать парсер  дизер на php

**Comment by superdima05** [comment]
Парсер дилер имеется ввиду скрипт для скачивания?

**Comment by vitaliy1379** [comment]
ну да типа так
https://aux.app/search

**Comment by vitaliy1379** [comment]
тупо в поиске вводишь  и тебе результат и там можно скачать

**Comment by vitaliy1379** [comment]
как есть звук ком ,вк или ютуб

**Comment by vitaliy1379** [comment]
нужен парсер дизер на php

**Comment by vitaliy1379** [comment]
чтоб визуально загружался и там строка поиска  и выводились треки и скачать

**Comment by superdima05** [comment]
Т.к. я backend developer, то реализовать данный сайт не смогу.

**Comment by superdima05** [comment]
Но для скачивания можно использовать мой скрипт, установив его на Heroku и библиотеку для PHP - https://github.com/PouleR/deezer-api. [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/superdima05/deezer-grabber-server/tree/heroku) (Tested on United States)

**Comment by vitaliy1379** [comment]
https://get-tune.cc/ типа так не сможете я вас понял а вообще не знаете как можно обойти лимит 30 секунд ну там если через апи делать то играет трек 30 секунд

**Comment by superdima05** [comment]
Через API получить полную версию невозможно, можно развернуть данный скрипт и делать запросы на него и получать FLAC файл

**Comment by superdima05** [comment]
Через API получить полную версию невозможно, можно развернуть данный скрипт и делать запросы на него и получать FLAC файл

**Comment by vitaliy1379** [comment]
то есть тот сайт также обходить апи как у вас скрипт

**Comment by superdima05** [comment]
https://get-tune.cc/? Он не стримит с Deezer

**Comment by superdima05** [comment]
Сайт сам хранит треки на серверах

**Comment by vitaliy1379** [comment]
он стримит вк

**Comment by superdima05** [comment]
Может быть, но для пользователя стриминг уже идет с их серверов

**Comment by vitaliy1379** [comment]
да там куча сайтов кто вк кто все разом как тот

**Comment by superdima05** [comment]
`https://stream.get-tune.cc/listen/99306789/TXBmS1VQWkdqWk9lMEdUMWRHbzdBQVNoS05DWXcvMzBjc3BFdTFNVTdFaHRpQ29yMGVxc0VNc3EvQm5URUhZaFZNcFZTV2FqZTJiUytLK0EzTEJLUzVmNzZmZmR5UVVkbjBEUWJCeDY0cWhPWmRYYnRJN0p6cHBEZEx3NVJEWkQ/an-lorak-ty-ecshe-lyubish_(get-tune.net).mp3` - вот пример ссылки

**Comment by vitaliy1379** [comment]
это имитация

**Comment by superdima05** [comment]
Возможно

**Comment by vitaliy1379** [comment]
к примеру вот сайт https://musicat.net/ парсит  https://zvuk.com/

**Comment by vitaliy1379** [comment]
там по id треку поймете

**Comment by vitaliy1379** [comment]
он еще парсит майл ок вк ютуб ну как вы сами зададите в админке

**Comment by vitaliy1379** [comment]
https://zvuk.com/track/67529723   источник   

и парсер https://musicat.net/track/67529723

**Comment by superdima05** [comment]
Хорошо, как это относится к данному проекту?

**Comment by vitaliy1379** [comment]
не ,я просто ищу кто может реализовать дизер ,вот и подумал мало ли повезет с вами

**Comment by superdima05** [comment]
К сожалению помочь не могу, надо обращаться к frontend разработчику

**Comment by vitaliy1379** [comment]
или подскажите где найти таких людей

**Comment by superdima05** [comment]
Не смогу тут помочь

**Comment by vitaliy1379** [comment]
спасибо хоть на этом, буду искать

**Comment by superdima05** [comment]
На https://fl.ru можно посмотреть

**Comment by vitaliy1379** [comment]
кстати если для себя , то есть дизер апк  он уже с премиум подпиской на андроид

**Comment by superdima05** [comment]
Я видел, но данный проект нужен для другого http://github.com/superdima05/deezer-grabber
